data "aws_caller_identity" "current" {}

data "aws_caller_identity" "swg_credentials" {
  count = local.swg_credential_managed_kms_enabled ? 1 : 0

  provider = aws.swg_credentials
}

data "aws_partition" "current" {}

locals {
  resource_name_prefix = "${var.project_name}-${var.environment}-data"
  secret_name_prefix   = "${var.project_name}/${var.environment}/data"

  provider_tags = merge(var.tags, {
    Project     = var.project_name
    Environment = var.environment
    Stack       = "aws-standalone-rbi-data"
    Owner       = "rbi"
  })

  common_tags = merge(local.provider_tags, {
    TerraformRoot = "envs/prod/us-east-1/data"
  })

  secret_names = {
    for secret_key, secret in var.rbi_secret_metadata :
    secret_key => secret.name != null ? secret.name : "${local.secret_name_prefix}/${secret_key}"
  }

  swg_handoff_secret_arn_pattern = "arn:${data.aws_partition.current.partition}:secretsmanager:${var.aws_region}:${data.aws_caller_identity.current.account_id}:secret:${local.secret_names["swg_handoff_shared_secret"]}-*"
  swg_handoff_current_stage      = "AWSCURRENT"
  swg_handoff_previous_stage     = "AWSPREVIOUS"
  swg_handoff_read_stage_order   = [local.swg_handoff_current_stage, local.swg_handoff_previous_stage]

  swg_credential_secret_name      = var.swg_credential_secret_name != "" ? var.swg_credential_secret_name : "${var.project_name}/${var.environment}/credentials/swg-rbi-secret-reader"
  swg_credential_reader_user_name = var.swg_credential_reader_user_name != "" ? var.swg_credential_reader_user_name : "${var.project_name}-${var.environment}-swg-handoff-secret-reader"
  swg_credential_reader_enabled   = var.swg_credential_secret_enabled && var.swg_credential_reader_user_enabled
  swg_credential_managed_kms_enabled = (
    var.swg_credential_secret_enabled &&
    var.swg_credential_secret_kms_key_id == ""
  )
  swg_credential_secret_arn_pattern = local.swg_credential_managed_kms_enabled ? "arn:${data.aws_partition.current.partition}:secretsmanager:${var.swg_credential_secret_region}:${data.aws_caller_identity.swg_credentials[0].account_id}:secret:${local.swg_credential_secret_name}-*" : null
  swg_credential_secret_kms_key_id  = var.swg_credential_secret_kms_key_id != "" ? var.swg_credential_secret_kms_key_id : try(module.swg_credentials_kms[0].key_arn, null)

  swg_handoff_secret_overrides = {
    description = "RBI-owned SWG to RBI handoff shared secret. The secret container, IAM policy, and KMS permissions are Terraform-managed; secret values are generated by the repo bootstrap workflow and are not stored in Terraform state."
    tags = merge(
      coalesce(var.rbi_secret_metadata["swg_handoff_shared_secret"].tags, {}),
      {
        SecretMaterialManagedBy = "rbi-bootstrap-secrets"
        TerraformCreatesVersion = "false"
      }
    )
    read_principal_arns = local.swg_credential_reader_enabled ? distinct(concat(
      coalesce(var.rbi_secret_metadata["swg_handoff_shared_secret"].read_principal_arns, []),
      local.swg_credential_reader_user_arns
    )) : var.rbi_secret_metadata["swg_handoff_shared_secret"].read_principal_arns
  }

  rbi_secret_metadata = merge(var.rbi_secret_metadata, {
    swg_handoff_shared_secret = merge(var.rbi_secret_metadata["swg_handoff_shared_secret"], {
      inherit_default_read_principals = coalesce(var.rbi_secret_metadata["swg_handoff_shared_secret"].inherit_default_read_principals, true)
    }, local.swg_handoff_secret_overrides)
  })

  swg_credential_secrets = var.swg_credential_secret_enabled ? {
    swg_rbi_secret_reader = {
      name                            = local.swg_credential_secret_name
      description                     = "SWG credential secret container used by proxy pods to read RBI handoff signing secrets. Terraform creates the container and access policy only; credential values are not stored in Terraform state."
      kms_key_id                      = local.swg_credential_secret_kms_key_id
      inherit_default_read_principals = true
      tags = {
        RbiUse                  = "swg-credential-reader"
        SecretMaterialManagedBy = "operator-managed"
        TerraformCreatesVersion = "false"
      }
    }
  } : {}

  swg_credential_reader_user_arns = local.swg_credential_reader_enabled ? [
    aws_iam_user.swg_credential_reader[0].arn
  ] : []

  secret_arn_patterns = [
    for secret_name in values(local.secret_names) :
    "arn:${data.aws_partition.current.partition}:secretsmanager:${var.aws_region}:${data.aws_caller_identity.current.account_id}:secret:${secret_name}-*"
  ]

  rotation_placeholders = {
    for secret_key in keys(var.rbi_secret_metadata) :
    secret_key => {
      secret_key               = secret_key
      create_iam_role          = true
      rotation_lambda_arn      = lookup(var.rotation_lambda_arns, secret_key, null)
      automatically_after_days = var.default_rotation_days
    }
  }

  public_certificates = var.public_certificate_domain_name == "" ? {} : {
    public_endpoint = {
      domain_name               = var.public_certificate_domain_name
      subject_alternative_names = var.public_certificate_subject_alternative_names
      hosted_zone_id            = var.public_certificate_hosted_zone_id != "" ? var.public_certificate_hosted_zone_id : null
      create_route53_records    = var.public_certificate_hosted_zone_id != ""
      wait_for_validation       = var.wait_for_public_certificate_validation
      tags = {
        RbiUse = "public-endpoint"
      }
    }
  }

  rotation_log_groups = {
    for rotation_key in keys(local.rotation_placeholders) :
    "rotation_${rotation_key}" => {
      name              = "/aws/lambda/${local.resource_name_prefix}-${rotation_key}-rotation"
      retention_in_days = var.observability_log_retention_days
      kms_key_id        = var.observability_log_group_kms_key_id
      tags = {
        RbiUse = "rotation-placeholder"
      }
    }
  }

  observability_event_rules = {
    secrets_manager_audit = {
      name        = "${local.resource_name_prefix}-secrets-audit"
      description = "Audit RBI Secrets Manager secret version and rotation API activity."
      event_pattern = jsonencode({
        source      = ["aws.secretsmanager"]
        detail-type = ["AWS API Call via CloudTrail"]
        detail = {
          eventSource = ["secretsmanager.amazonaws.com"]
          eventName = [
            "CancelRotateSecret",
            "DeleteSecret",
            "PutSecretValue",
            "RestoreSecret",
            "RotateSecret",
            "UpdateSecret",
            "UpdateSecretVersionStage",
          ]
        }
      })
      target_arns = var.observability_event_target_arns
      tags = {
        RbiUse = "secrets-audit"
      }
    }

    kms_secrets_audit = {
      name        = "${local.resource_name_prefix}-kms-audit"
      description = "Audit KMS decrypt operations for RBI secret material."
      event_pattern = jsonencode({
        source      = ["aws.kms"]
        detail-type = ["AWS API Call via CloudTrail"]
        detail = {
          eventSource = ["kms.amazonaws.com"]
          eventName   = ["Decrypt", "GenerateDataKey", "Encrypt"]
        }
      })
      target_arns = var.observability_event_target_arns
      tags = {
        RbiUse = "kms-audit"
      }
    }

    mtls_certificate_audit = {
      name        = "${local.resource_name_prefix}-mtls-audit"
      description = "Audit ACM and ACM PCA API activity for RBI mTLS metadata."
      event_pattern = jsonencode({
        source      = ["aws.acm", "aws.acm-pca"]
        detail-type = ["AWS API Call via CloudTrail"]
        detail = {
          eventSource = ["acm.amazonaws.com", "acm-pca.amazonaws.com"]
        }
      })
      target_arns = var.observability_event_target_arns
      tags = {
        RbiUse = "mtls-audit"
      }
    }
  }
}

resource "aws_iam_user" "swg_credential_reader" {
  count = local.swg_credential_reader_enabled ? 1 : 0

  name = local.swg_credential_reader_user_name

  tags = merge(local.common_tags, {
    Module                    = "iam"
    RbiUse                    = "swg-handoff-secret-reader"
    TerraformCreatesAccessKey = "false"
  })
}

data "aws_iam_policy_document" "swg_credential_reader_kms_key_policy" {
  count = local.swg_credential_reader_enabled ? 1 : 0

  statement {
    sid    = "AllowSwgCredentialReaderDecryptHandoffSecret"
    effect = "Allow"
    actions = [
      "kms:Decrypt",
      "kms:DescribeKey",
    ]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = local.swg_credential_reader_user_arns
    }

    condition {
      test     = "StringEquals"
      variable = "kms:ViaService"
      values   = ["secretsmanager.${var.aws_region}.${data.aws_partition.current.dns_suffix}"]
    }

    condition {
      test     = "ArnLike"
      variable = "kms:EncryptionContext:SecretARN"
      values   = [local.swg_handoff_secret_arn_pattern]
    }
  }
}

module "kms" {
  source = "../../../../modules/kms"

  name        = "secrets"
  environment = var.environment
  description = "RBI ${var.environment} data key for Secrets Manager metadata and future rotation workflows."
  alias_names = ["alias/${local.resource_name_prefix}-secrets"]

  admin_principal_arns         = var.kms_admin_principal_arns
  decrypt_principal_arns       = var.swg_read_role_arns
  allowed_secret_arn_patterns  = local.secret_arn_patterns
  deletion_window_in_days      = 30
  enable_key_rotation          = true
  source_policy_documents      = local.swg_credential_reader_enabled ? [data.aws_iam_policy_document.swg_credential_reader_kms_key_policy[0].json] : []
  secret_writer_principal_arns = []

  tags = local.common_tags
}

module "secrets" {
  source = "../../../../modules/secrets"

  secret_name_prefix          = local.secret_name_prefix
  resource_name_prefix        = local.resource_name_prefix
  default_kms_key_id          = module.kms.key_arn
  default_read_principal_arns = var.swg_read_role_arns
  secrets                     = local.rbi_secret_metadata
  rotation_placeholders       = local.rotation_placeholders
  rotation_kms_key_arn        = module.kms.key_arn

  tags = local.common_tags
}

module "swg_credentials_kms" {
  count = local.swg_credential_managed_kms_enabled ? 1 : 0

  source = "../../../../modules/kms"

  providers = {
    aws = aws.swg_credentials
  }

  name        = "swg-credential-secrets"
  environment = var.environment
  description = "SWG ${var.environment} credential secret key for RBI handoff reader credentials."
  alias_names = ["alias/${local.resource_name_prefix}-swg-credential-secrets"]

  admin_principal_arns         = []
  decrypt_principal_arns       = var.swg_credential_secret_read_principal_arns
  allowed_secret_arn_patterns  = [local.swg_credential_secret_arn_pattern]
  deletion_window_in_days      = 30
  enable_key_rotation          = true
  secret_writer_principal_arns = []

  tags = merge(local.common_tags, {
    RbiUse = "swg-credential-reader"
  })
}

module "swg_credentials" {
  source = "../../../../modules/secrets"

  providers = {
    aws = aws.swg_credentials
  }

  secret_name_prefix          = "${var.project_name}/${var.environment}/credentials"
  resource_name_prefix        = "${local.resource_name_prefix}-swg-credentials"
  default_kms_key_id          = local.swg_credential_secret_kms_key_id
  default_read_principal_arns = var.swg_credential_secret_read_principal_arns
  secrets                     = local.swg_credential_secrets
  rotation_placeholders       = {}
  rotation_kms_key_arn        = null

  tags = merge(local.common_tags, {
    SecretMaterialManagedBy = "operator-managed"
    TerraformCreatesVersion = "false"
  })
}

data "aws_iam_policy_document" "swg_credential_reader" {
  count = local.swg_credential_reader_enabled ? 1 : 0

  statement {
    sid    = "AllowReadSwgHandoffSecret"
    effect = "Allow"
    actions = [
      "secretsmanager:DescribeSecret",
      "secretsmanager:GetSecretValue",
      "secretsmanager:ListSecretVersionIds",
    ]
    resources = [
      module.secrets.secret_arns["swg_handoff_shared_secret"],
    ]
  }

  statement {
    sid    = "AllowDecryptSwgHandoffSecret"
    effect = "Allow"
    actions = [
      "kms:Decrypt",
      "kms:DescribeKey",
    ]
    resources = ["*"]

    condition {
      test     = "StringEquals"
      variable = "kms:ViaService"
      values   = ["secretsmanager.${var.aws_region}.${data.aws_partition.current.dns_suffix}"]
    }

    condition {
      test     = "ArnLike"
      variable = "kms:EncryptionContext:SecretARN"
      values   = [local.swg_handoff_secret_arn_pattern]
    }
  }
}

resource "aws_iam_user_policy" "swg_credential_reader" {
  count = local.swg_credential_reader_enabled ? 1 : 0

  name   = "ReadCloudsecRbiSwgHandoffSecret"
  user   = aws_iam_user.swg_credential_reader[0].name
  policy = data.aws_iam_policy_document.swg_credential_reader[0].json
}

module "mtls" {
  source = "../../../../modules/mtls"

  public_certificates           = local.public_certificates
  private_cas                   = var.private_cas
  private_ca_permissions        = var.private_ca_permissions
  trust_bundles                 = var.trust_bundles
  trust_bundle_parameter_prefix = "/${var.project_name}/${var.environment}/mtls/trust-bundles"

  tags = local.common_tags
}

module "observability" {
  source = "../../../../modules/observability"

  log_groups  = local.rotation_log_groups
  event_rules = local.observability_event_rules

  tags = local.common_tags
}
