apiVersion: v1
kind: Secret
metadata:
  name: rbi-worker-pool-secret
  namespace: cloudsec-rbi-workers
  labels:
    app.kubernetes.io/name: cloudsec-remote-browser
    app.kubernetes.io/component: rbi-worker-pool
    cloudsec.cisco.com/rbi-plane: worker
type: Opaque
stringData:
  pool-shared-secret: replace-me
---
apiVersion: v1
kind: Secret
metadata:
  name: rbi-session-worker-secret
  namespace: cloudsec-rbi-workers
  labels:
    app.kubernetes.io/name: cloudsec-remote-browser
    app.kubernetes.io/component: rbi-session-worker
    cloudsec.cisco.com/rbi-plane: worker
type: Opaque
stringData:
  worker-token: replace-me
  turn-username: replace-me
  turn-password: replace-me
