apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbi-worker
  namespace: cloudsec-rbi-workers
  labels:
    app.kubernetes.io/name: cloudsec-remote-browser
    app.kubernetes.io/component: rbi-worker
    cloudsec.cisco.com/rbi-plane: worker
automountServiceAccountToken: false
