apiVersion: v1
kind: Namespace
metadata:
  name: cloudsec-rbi-workers
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    cloudsec.cisco.com/rbi-plane: worker
